import Solar from "./assets/green-assist-solar.png"
import CartIcon from "./assets/green-assist-cart-icon.svg"
import CircleRings from "./assets/green-assist-circle-rings.svg"
import FlagIcon from "./assets/green-assist-flag-icon.svg"
import Hamburger from "./assets/green-assist-hamburger.svg"
import Logo from "./assets/green-assist-logo.png"
import MessageIcon from "./assets/green-assist-message-icon.svg"
import Mobil from "./assets/green-assist-mobil.jpeg"
import MoneyIcon from "./assets/green-assist-money-icon.svg"
import Money from "./assets/green-assist-money.png"
import PeopleIcon from "./assets/green-assist-people-icon.svg"
import Refinery from "./assets/green-assist-refinery.png"
import Smoke from "./assets/green-assist-smoke.png"

export {Solar, CartIcon, CircleRings, FlagIcon, Hamburger, Logo, MessageIcon, Mobil, Money, MoneyIcon, PeopleIcon, Refinery, Smoke};